version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565" # minecraft
      - "8100:80" # bluemap
    restart: always
    environment:
      TYPE: "FABRIC"
      PACKWIZ_URL: "https://ryleu.me/christmas-modpack-2023/packwiz/pack.toml"
      EULA: true
      MOTD: "CCH Server"
      DIFFICULTY: "HARD"
      SEED: ""
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 6
      OPS_FILE: "https://ryleu.me/christmas-modpack-2023/minecraft/ops.json"
      WHITELIST_FILE: "https://ryleu.me/christmas-modpack-2023/minecraft/whitelist.json"
      MEMORY: "6G"
      USE_AIKAR_FLAGS: true
      VERSION: "1.20.2"
    volumes:
      - ./data:/data
