name = "Christmas Modpack 2023"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e7bb70d953e222013659233ba97d7168aca719549540095df3405b2a8f319b8"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
