name = "Christmas Modpack 2023"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72bff77a56eacfa6e1106c839b0ed62319a3bf32e96eaf704097f7cb9feb9bd8"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
