name = "Christmas Modpack 2023"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d13c2427e7f593b7b623887a305eabada10a5f44198c662192b1604bb6b7db03"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
