name = "Christmas Modpack 2023"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ff67ef42438a60f42cdfe73bd107e8f66f4a44100f92c81085845ef3d71a84c"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
