name: Pages Deploy
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy Files
        run: |
          rm -rf ../build/
          mkdir -p ../build/
          cp -r ./* ../build/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../build/
          keep_files: true
          full_commit_message: update repo
